name: Deploy to NAS_Website Portfolio
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to NAS_Website Portfolio
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USERNAME }}
        key: ${{ secrets.NAS_SSH_KEY }}
        timeout: 10m
        debug: true 
        script: |
          cd /volume1/docker/website
          git pull origin main
          /usr/local/bin/docker compose down -v || true  # --remove-orphans 제거
          /usr/local/bin/docker compose build --no-cache
          /usr/local/bin/docker compose up -d --force-recreate --pull
          /usr/local/bin/docker compose ps
          /usr/local/bin/docker system prune -f
          /usr/local/bin/docker compose logs node-app
          echo "Deploy 완료: $(date)"
