name: Deploy to NAS_Website Portfolio
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to NAS_Website Portfolio
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USERNAME }}
        key: ${{ secrets.NAS_SSH_KEY }}
        timeout: 10m
        debug: true 
        script: |
          cd /volume1/docker/website
          git pull origin main
          docker-compose down  || true
          docker compose build --no-cache --force-rm
          docker-compose up -d --build --force-recreate
          docker system prune -f
          echo "Deploy 완료: $(date)"
